<Project Sdk="Microsoft.NET.Sdk.Worker">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>2f6a2a5c-9d24-42d4-a0e0-9be9a0e70f21</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Definition\ServiceDefaults\ServiceDefaults.csproj" />
        <ProjectReference Include="..\..\Definition\EntityFramework\EntityFramework.csproj" />
    </ItemGroup>
</Project>
