<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>9b1d6f21-0b5f-4a9e-9e3a-2f33a05d5f2d</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Nats" />
        <PackageReference Include="Aspire.Hosting.JavaScript" />
        <PackageReference Include="Aspire.Hosting.Qdrant" />
        <PackageReference Include="Aspire.Hosting.Redis" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Perigon\Perigon.AspNetCore\Perigon.AspNetCore.csproj" IsAspireProjectResource="false" />
        <ProjectReference Include="..\Services\ApiService\ApiService.csproj" />
    </ItemGroup>
</Project>
