@AdminService_HostAddress = https://localhost:7001/api/

POST {{AdminService_HostAddress}}/systemuser/login
Accept: application/json
{
  "userName": "admin@default.com",
  "password":"Ater.Default.2026"
}

###
